from graphics import *
win=GraphWin('Shapes')
center=Point(100,100)
circ=Circle(center,30)
circ.setFill('red')
circ.draw(win)
label=Text(center,"Red Circle")
label.draw(win)
win.getMouse()
win.close()
